# ============ 基础配置 ============
baseURL = "https://jingyil.github.io"
#baseURL = "http://10.255.255.254:1313"
title = "我的网站"
theme = "book"

# 构建配置
[pagination]
  pagerSize = 20

[caches]
  [caches.images]
    dir = ':cacheDir/images'

enableGitInfo = true
enableRobotsTXT = true

# Hugo Book主题需要的配置
[params]
  # 强制使用中文
  BookLanguage = "zh-CN"
  
  # 搜索功能
  BookSearch = true
  
  # 启用章节链接
  BookPortableLinks = true
  
  # 启用目录大纲
  BookToC = true

# 税收分类（博客需要）
[taxonomies]
  category = "categories"
  tag = "tags"

ignoreFiles = ["themes/.*/exampleSite/.*"]
